# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-17 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=255)),
                ('squad_market_value', models.PositiveIntegerField(null=True)),
                ('crest_url', models.URLField(null=True)),
            ],
        ),
    ]
