# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255, null=True)),
                ('short_name', models.CharField(max_length=255, null=True)),
                ('squad_market_value', models.PositiveIntegerField(null=True)),
                ('crest_url', models.URLField(null=True)),
                ('competition', models.ManyToManyField(to='competition.Competition')),
            ],
        ),
    ]
