# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-22 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
        ('team', '0002_auto_20161022_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='competition',
        ),
        migrations.AddField(
            model_name='team',
            name='competition',
            field=models.ManyToManyField(to='competition.Competition'),
        ),
    ]
