# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-16 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20161014_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='squad_market_value_currency',
        ),
        migrations.AlterField(
            model_name='team',
            name='squad_market_value',
            field=models.PositiveIntegerField(),
        ),
    ]
