# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(choices=[('Keeper', 'Torwart'), ('Right-Back', 'Rechter Außenverteidiger'), ('Centre Back', 'Innenverteidiger'), ('Left-Back', 'Linker Außenverteidiger'), ('Defensive Midfield', 'Defensives Mittelfeld'), ('Left Midfield', 'Linkes Mittelfeld'), ('Central Midfield', 'Zentrales Mittelfeld'), ('Midfield', 'Mittelfeld'), ('Mittelfeld', 'Mittelfeld'), ('Right Midfield', 'Rechtes Mittelfeld'), ('Attacking Midfield', 'Offensives Mittelfeld'), ('Right Wing', 'Rechter Flügel'), ('Secondary Striker', 'Hängende Spitze'), ('Centre Forward', 'Stürmer'), ('Left Wing', 'Linker Flügel')], max_length=255)),
                ('jersey_number', models.PositiveSmallIntegerField(null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('nationality', models.CharField(choices=[('Poland', 'Polen'), ('South Africa', 'Südafrika'), ('Cape Verde', 'Kap Verde'), ('Congo', 'Kongo'), ('Austria', 'Österreich'), ('Ecuador', 'Ecuador'), ('Egypt', 'Ägypten'), ('Chile', 'Chile'), ('Gabon', 'Gabun'), ('Denmark', 'Dänemark'), ('Burkina Faso', 'Burkina Faso'), ('Netherlands', 'Niederlande'), ('Jamaica', 'Jamaika'), ('Montenegro', 'Montenegro'), ('Iran', 'Iran'), ('Portugal', 'Portugal'), ('Haiti', 'Haiti'), ('England', 'England'), ('United States', 'Vereinigte Staaten'), ('Venezuela', 'Venezuela'), ('Slovenia', 'Slovenien'), ('France', 'Frankreich'), ('Lithuania', 'Lettland'), ('Guadeloupe', 'Guadeloupe'), ('Ukraine', 'Ukraine'), ('Argentina', 'Argentinien'), ('Luxembourg', 'Luxemburg'), ('Korea, South', 'Südkorea'), ('Germany', 'Deutschland'), ('Mexico', 'Mexiko'), ('Croatia', 'Kroatien'), ('Madagascar', 'Madagaskar'), ('The Gambia', 'Gambia'), ('Brazil', 'Brasilien'), ('Sweden', 'Schweden'), ('Russia', 'Russland'), ('Canada', 'Kanada'), ('Algeria', 'Algerien'), ('Armenia', 'Armenien'), ('Belgium', 'Belgien'), ('Uganda', 'Uganda'), ('Dominican Republic', 'Dominikanische Republik'), ('Paraguay', 'Paraguay'), ('Kosovo', 'Kosovo'), ('Morocco', 'Marokko'), ('Finland', 'Finnland'), ('Czech Republic', 'Tschechien'), ('Peru', 'Peru'), ('Guinea', 'Guinea'), ('Israel', 'Israel'), ('Sierra Leone', 'Sierra Leone'), ('Latvia', 'Lettland'), ('Turkey', 'Turkey'), ('Macedonia', 'Mazedonien'), ('Costa Rica', 'Costa Rica'), ('Ireland', 'Irland'), ('Serbia', 'Serbien'), ('Slovakia', 'Slowakei'), ('Spain', 'Spanien'), ('Nigeria', 'Nigeria'), ('Iceland', 'Island'), ('Switzerland', 'Schweiz'), ('Italy', 'Italien'), ('Guine', 'Guinea'), ('Kenya', 'Kenia'), ('Australia', 'Australien'), ('Estonia', 'Estland'), ('Kazakhstan', 'Kasachstan'), ('Cameroon', 'Kamerun'), ('Senegal', 'Senegal'), ('Bulgaria', 'Bulgarien'), ('Norway', 'Norwegen'), ('Togo', 'Togo'), ('Congo DR', 'Demokratische Republik Kongo'), ('Antigua and Barbuda', 'Antigua und Barbuda'), ('Honduras', 'Honduras'), ('Colombia', 'Kolumbien'), ('Ghana', 'Ghana'), ('Angola', 'Angola'), ('Romania', 'Rumänien'), ('Bosnia-Herzegovina', 'Bosnien und Herzegowina'), ('Japan', 'Japan'), ('Uruguay', 'Uruguay'), ('Equatorial Guinea', 'Äquatorialguinea'), ('Greece', 'Griechenland'), ('Palästina', 'Palästina'), ('New Zealand', 'Neuseeland'), ('Hungary', 'Ungarn'), ('Tunisia', 'Tunesien'), ('Northern Ireland', 'Nordirland'), ("Cote d'Ivoire", 'Elfenbeinküste'), ('Georgia', 'Georgien'), ('Wales', 'Wales'), ('Curacao', 'Curaçao'), ('Benin', 'Benin'), ('Albania', 'Albanien'), ('Scotland', 'Schottland'), ('Mali', 'Mali'), ('Martinique', 'Martinique'), ('French-Guiana', 'Französisch-Guayana')], max_length=255)),
                ('contract_until', models.DateField(null=True)),
                ('market_value', models.PositiveIntegerField(db_index=True, null=True)),
                ('image', models.URLField(null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team')),
            ],
            options={
                'ordering': ['jersey_number'],
            },
        ),
    ]
