# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-18 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(choices=[('Keeper', 'Torwart'), ('Right-Back', 'Rechter Außenverteidiger'), ('Centre Back', 'Innenverteidiger'), ('Left-Back', 'Linker Außenverteidiger'), ('Defensive Midfield', 'Defensives Mittelfeld'), ('Central Midfield', 'Zentrales Mittelfeld'), ('Attacking Midfield', 'Offensives Mittelfeld'), ('Right Wing', 'Rechter Flügel'), ('Centre Forward', 'Stürmer'), ('Left Wing', 'Linker Flügel')], max_length=255)),
                ('jersey_number', models.PositiveSmallIntegerField()),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=255)),
                ('contract_until', models.DateField(null=True)),
                ('market_value', models.PositiveIntegerField(null=True)),
                ('image', models.URLField(null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
