# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-17 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(choices=[(1, 'Keeper'), (2, 'Right-Back'), (4, 'Centre Back'), (3, 'Left-Back'), (6, 'Defensive Midfield'), (8, 'Central Midfield'), (10, 'Attacking Midfield'), (7, 'Right Wing'), (9, 'Centre Forward'), (11, 'Left Wing')], max_length=255)),
                ('jersey_number', models.PositiveSmallIntegerField()),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=255)),
                ('contract_until', models.DateField(null=True)),
                ('market_value', models.PositiveIntegerField(null=True)),
                ('image', models.URLField(null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
