# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-13 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='contract_until',
            field=models.DateField(null=True),
        ),
    ]
