# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 10:28
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
