# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-23 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20161023_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
