# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20170108_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
