# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-14 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20161014_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
