# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_auto_20170122_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.CharField(choices=[('Poland', 'Polen'), ('South Africa', 'Südafrika'), ('Cape Verde', 'Kap Verde'), ('Congo', 'Kongo'), ('Austria', 'Österreich'), ('Ecuador', 'Ecuador'), ('Egypt', 'Ägypten'), ('Chile', 'Chile'), ('Gabon', 'Gabun'), ('Denmark', 'Dänemark'), ('Burkina Faso', 'Burkina Faso'), ('Netherlands', 'Niederlande'), ('Jamaica', 'Jamaika'), ('Montenegro', 'Montenegro'), ('Iran', 'Iran'), ('Portugal', 'Portugal'), ('Haiti', 'Haiti'), ('England', 'England'), ('United States', 'Vereinigte Staaten'), ('Venezuela', 'Venezuela'), ('Slovenia', 'Slovenien'), ('France', 'Frankreich'), ('Lithuania', 'Lettland'), ('Guadeloupe', 'Guadeloupe'), ('Ukraine', 'Ukraine'), ('Argentina', 'Argentinien'), ('Luxembourg', 'Luxemburg'), ('Korea, South', 'Südkorea'), ('Germany', 'Deutschland'), ('Mexico', 'Mexiko'), ('Croatia', 'Kroatien'), ('Madagascar', 'Madagaskar'), ('The Gambia', 'Gambia'), ('Brazil', 'Brasilien'), ('Sweden', 'Schweden'), ('Russia', 'Russland'), ('Canada', 'Kanada'), ('Algeria', 'Algerien'), ('Armenia', 'Armenien'), ('Belgium', 'Belgien'), ('Uganda', 'Uganda'), ('Dominican Republic', 'Dominikanische Republik'), ('Paraguay', 'Paraguay'), ('Kosovo', 'Kosovo'), ('Morocco', 'Marokko'), ('Finland', 'Finnland'), ('Czech Republic', 'Tschechien'), ('Peru', 'Peru'), ('Guinea', 'Guinea'), ('Israel', 'Israel'), ('Sierra Leone', 'Sierra Leone'), ('Latvia', 'Lettland'), ('Turkey', 'Turkey'), ('Macedonia', 'Mazedonien'), ('Costa Rica', 'Costa Rica'), ('Ireland', 'Irland'), ('Serbia', 'Serbien'), ('Slovakia', 'Slowakei'), ('Spain', 'Spanien'), ('Nigeria', 'Nigeria'), ('Iceland', 'Island'), ('Switzerland', 'Schweiz'), ('Italy', 'Italien'), ('Guine', 'Guinea'), ('Kenya', 'Kenia'), ('Australia', 'Australien'), ('Estonia', 'Estland'), ('Kazakhstan', 'Kasachstan'), ('Cameroon', 'Kamerun'), ('Senegal', 'Senegal'), ('Bulgaria', 'Bulgarien'), ('Norway', 'Norwegen'), ('Togo', 'Togo'), ('Congo DR', 'Demokratische Republik Kongo'), ('Antigua and Barbuda', 'Antigua und Barbuda'), ('Honduras', 'Honduras'), ('Colombia', 'Kolumbien'), ('Ghana', 'Ghana'), ('Angola', 'Angola'), ('Romania', 'Rumänien'), ('Bosnia-Herzegovina', 'Bosnien und Herzegowina'), ('Japan', 'Japan'), ('Uruguay', 'Uruguay'), ('Equatorial Guinea', 'Äquatorialguinea'), ('Greece', 'Griechenland'), ('Palästina', 'Palästina'), ('New Zealand', 'Neuseeland'), ('Hungary', 'Ungarn'), ('Tunisia', 'Tunesien'), ('Northern Ireland', 'Nordirland'), ("Cote d'Ivoire", 'Elfenbeinküste'), ('Georgia', 'Georgien'), ('Wales', 'Wales'), ('Curacao', 'Curaçao'), ('Benin', 'Benin'), ('Albania', 'Albanien'), ('Scotland', 'Schottland'), ('Mali', 'Mali'), ('Martinique', 'Martinique'), ('French-Guiana', 'Französisch-Guayana'), ('Central African Republic', 'Zentralafrikanische Republik'), ('Argentinien', 'Argentinien')], max_length=255),
        ),
    ]
