# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0011_auto_20170122_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.CharField(choices=[('Albania', 'Albanien'), ('Algeria', 'Algerien'), ('Angola', 'Angola'), ('Antigua and Barbuda', 'Antigua und Barbuda'), ('Argentina', 'Argentinien'), ('Argentinien', 'Argentinien'), ('Armenia', 'Armenien'), ('Australia', 'Australien'), ('Austria', 'Österreich'), ('Belgium', 'Belgien'), ('Benin', 'Benin'), ('Bosnia-Herzegovina', 'Bosnien und Herzegowina'), ('Brazil', 'Brasilien'), ('Bulgaria', 'Bulgarien'), ('Burkina Faso', 'Burkina Faso'), ('Cameroon', 'Kamerun'), ('Canada', 'Kanada'), ('Cape Verde', 'Kap Verde'), ('Central African Republic', 'Zentralafrikanische Republik'), ('Chile', 'Chile'), ('Colombia', 'Kolumbien'), ('Congo', 'Kongo'), ('Congo DR', 'Demokratische Republik Kongo'), ('Costa Rica', 'Costa Rica'), ("Cote d'Ivoire", 'Elfenbeinküste'), ('Croatia', 'Kroatien'), ('Curacao', 'Curaçao'), ('Czech Republic', 'Tschechien'), ('Denmark', 'Dänemark'), ('Dominican Republic', 'Dominikanische Republik'), ('Ecuador', 'Ecuador'), ('Egypt', 'Ägypten'), ('England', 'England'), ('Estonia', 'Estland'), ('Equatorial Guinea', 'Äquatorialguinea'), ('Finland', 'Finnland'), ('France', 'Frankreich'), ('French-Guiana', 'Französisch-Guayana'), ('Gabon', 'Gabun'), ('Georgia', 'Georgien'), ('Germany', 'Deutschland'), ('Ghana', 'Ghana'), ('Greece', 'Griechenland'), ('Griechenland', 'Griechenland'), ('Guadeloupe', 'Guadeloupe'), ('Guine', 'Guinea'), ('Guinea', 'Guinea'), ('Haiti', 'Haiti'), ('Honduras', 'Honduras'), ('Hungary', 'Ungarn'), ('Iceland', 'Island'), ('Iran', 'Iran'), ('Ireland', 'Irland'), ('Israel', 'Israel'), ('Italy', 'Italien'), ('Jamaica', 'Jamaika'), ('Japan', 'Japan'), ('Kazakhstan', 'Kasachstan'), ('Kenya', 'Kenia'), ('Korea, South', 'Südkorea'), ('Kosovo', 'Kosovo'), ('Latvia', 'Lettland'), ('Lithuania', 'Lettland'), ('Luxembourg', 'Luxemburg'), ('Macedonia', 'Mazedonien'), ('Madagascar', 'Madagaskar'), ('Mali', 'Mali'), ('Martinique', 'Martinique'), ('Mexico', 'Mexiko'), ('Montenegro', 'Montenegro'), ('Morocco', 'Marokko'), ('Netherlands', 'Niederlande'), ('New Zealand', 'Neuseeland'), ('Nigeria', 'Nigeria'), ('Northern Ireland', 'Nordirland'), ('Norway', 'Norwegen'), ('Palästina', 'Palästina'), ('Paraguay', 'Paraguay'), ('Peru', 'Peru'), ('Poland', 'Polen'), ('Portugal', 'Portugal'), ('Romania', 'Rumänien'), ('Russia', 'Russland'), ('Scotland', 'Schottland'), ('Senegal', 'Senegal'), ('Serbia', 'Serbien'), ('Sierra Leone', 'Sierra Leone'), ('Slovakia', 'Slowakei'), ('Slovenia', 'Slovenien'), ('South Africa', 'Südafrika'), ('Spain', 'Spanien'), ('Spanien', 'Spanien'), ('Sweden', 'Schweden'), ('Switzerland', 'Schweiz'), ('The Gambia', 'Gambia'), ('Togo', 'Togo'), ('Tunisia', 'Tunesien'), ('Turkey', 'Turkey'), ('Uganda', 'Uganda'), ('Ukraine', 'Ukraine'), ('United States', 'Vereinigte Staaten'), ('Uruguay', 'Uruguay'), ('Venezuela', 'Venezuela'), ('Wales', 'Wales')], max_length=255),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('Keeper', 'Torwart'), ('Torwart', 'Torwart'), ('Abwehr', 'Verteidiger'), ('Left-Back', 'Linker Außenverteidiger'), ('Centre Back', 'Innenverteidiger'), ('Innenverteidiger', 'Innenverteidiger'), ('Right-Back', 'Rechter Außenverteidiger'), ('Midfield', 'Mittelfeld'), ('Mittelfeld', 'Mittelfeld'), ('Defensive Midfield', 'Defensives Mittelfeld'), ('Left Midfield', 'Linkes Mittelfeld'), ('Central Midfield', 'Zentrales Mittelfeld'), ('Right Midfield', 'Rechtes Mittelfeld'), ('Attacking Midfield', 'Offensives Mittelfeld'), ('Left Wing', 'Linker Flügel'), ('Secondary Striker', 'Hängende Spitze'), ('H&auml;ngende Spitze', 'Hängende Spitze'), ('Centre Forward', 'Stürmer'), ('Right Wing', 'Rechter Flügel')], max_length=255),
        ),
    ]
