# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-16 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0012_auto_20161016_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
