# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0028_auto_20170124_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('Abwehr', 'Abwehr'), ('Attacking Midfield', 'Offensives Mittelfeld'), ('Central Midfield', 'Zentrales Mittelfeld'), ('Centre Back', 'Innenverteidiger'), ('Centre Forward', 'Mittelstürmer'), ('Defensive Midfield', 'Defensives Mittelfeld'), ('Defensives Mittelfeld', 'Defensives Mittelfeld'), ('H&auml;ngende Spitze', 'Hängende Spitze'), ('Innenverteidiger', 'Innenverteidiger'), ('Keeper', 'Torwart'), ('Left Midfield', 'Linkes Mittelfeld'), ('Left Wing', 'Linker Flügel'), ('Left-Back', 'Linker Außenverteidiger'), ('Linker Verteidiger', 'Linker Außenverteidiger'), ('Linksau&szlig;en', 'Linksaußen'), ('Midfield', 'Mittelfeld'), ('Mittelfeld', 'Mittelfeld'), ('Mittelst&uuml;rmer', 'Mittelstürmer'), ('Offensives Mittelfeld', 'Offensives Mittelfeld'), ('Rechter Verteidiger', 'Rechter Außenverteidiger'), ('Rechtsau&szlig;en', 'Rechtsaußen'), ('Right Midfield', 'Rechtes Mittelfeld'), ('Right Wing', 'Rechtsaußen'), ('Right-Back', 'Rechter Außenverteidiger'), ('Secondary Striker', 'Hängende Spitze'), ('Torwart', 'Torwart'), ('Zentrales Mittelfeld', 'Zentrales Mittelfeld')], max_length=255),
        ),
    ]
