# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Geplant'), ('TIMED', 'Festgelegt'), ('POSTPONED', 'Verschoben'), ('IN_PLAY', 'Im Spiel'), ('CANCELED', 'Abgebrochen'), ('CANCELLED', 'Abgebrochen'), ('FINISHED', 'Beendet'), ('FT', 'FT')], db_index=True, max_length=255, null=True),
        ),
    ]
