# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='matchday',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
