# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-23 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='away_team_name',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='home_team_name',
        ),
    ]
