# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-17 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='goals_away_team',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='goals_home_team',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
