# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0002_auto_20170122_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='matchday',
            field=models.PositiveIntegerField(),
        ),
    ]
