# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-17 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0002_auto_20161017_1507'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PenaltyShooutout',
            new_name='PenaltyShootout',
        ),
        migrations.AlterField(
            model_name='odds',
            name='away_win',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='odds',
            name='draw',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='odds',
            name='home_win',
            field=models.FloatField(null=True),
        ),
    ]
