# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-26 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0003_auto_20170211_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixture',
            options={'ordering': ['status', '-date']},
        ),
    ]
