# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0004_auto_20170125_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='matchday',
            field=models.PositiveIntegerField(),
        ),
    ]
