# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('is_cup', models.BooleanField()),
                ('caption', models.CharField(max_length=255)),
                ('league', models.CharField(max_length=255)),
                ('year', models.PositiveSmallIntegerField()),
                ('current_matchday', models.PositiveSmallIntegerField()),
                ('number_of_matchdays', models.PositiveSmallIntegerField()),
                ('number_of_teams', models.PositiveSmallIntegerField()),
                ('number_of_games', models.PositiveSmallIntegerField()),
                ('last_updated', models.DateTimeField()),
            ],
            options={
                'ordering': ['caption'],
                'get_latest_by': 'last_updated',
            },
        ),
    ]
