# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-26 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'get_latest_by': 'last_updated', 'ordering': ['-year', 'caption']},
        ),
    ]
