# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-17 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='league',
            field=models.CharField(choices=[(('440', 'CL'), ('424', 'EC')), (('430', 'BL1'), ('431', 'BL2'))], max_length=255),
        ),
    ]
