# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-26 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_auto_20170226_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='logo',
            field=models.ImageField(null=True, upload_to='competition_logos'),
        ),
    ]
