# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_auto_20170121_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='image',
            field=models.ImageField(blank=True, upload_to='competition_images'),
        ),
    ]
