# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_auto_20161226_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
