# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-26 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_auto_20170226_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='logo',
        ),
    ]
