# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0007_auto_20170127_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
