# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-27 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0009_auto_20170227_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='logo',
            field=models.ImageField(null=True, upload_to='mediafiles/competition_logos'),
        ),
    ]
