# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-27 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0011_auto_20170227_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='logo',
        ),
    ]
