# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-10 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Away',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.PositiveIntegerField()),
                ('goals_against', models.PositiveIntegerField()),
                ('wins', models.PositiveIntegerField()),
                ('draws', models.PositiveIntegerField()),
                ('losses', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=255)),
                ('league', models.CharField(choices=[('430', 'BL1'), ('431', 'BL2'), ('433', 'DED'), ('428', 'EL1'), ('427', 'ELC'), ('434', 'FL1'), ('435', 'FL2'), ('436', 'PD'), ('426', 'PL'), ('439', 'PPL'), ('438', 'SA'), ('437', 'SD')], max_length=255)),
                ('year', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016)])),
                ('current_matchday', models.PositiveSmallIntegerField()),
                ('number_of_matchdays', models.PositiveSmallIntegerField()),
                ('number_of_teams', models.PositiveSmallIntegerField()),
                ('number_of_games', models.PositiveSmallIntegerField()),
                ('last_updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CupTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_caption', models.CharField(max_length=255)),
                ('matchday', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ExtraTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals_home_team', models.PositiveSmallIntegerField()),
                ('goals_away_team', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[(1, 'SCHEDULED'), (2, 'TIMED'), (3, 'POSTPONED'), (4, 'IN_PLAY'), (5, 'CANCELED'), (6, 'FINISHED')], max_length=255)),
                ('matchday', models.PositiveSmallIntegerField()),
                ('home_team_name', models.CharField(max_length=255)),
                ('away_team_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cup_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballData.CupTable')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupStanding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField()),
                ('team', models.CharField(max_length=255)),
                ('team_id', models.PositiveSmallIntegerField()),
                ('played_games', models.PositiveSmallIntegerField()),
                ('crest_uri', models.URLField(null=True)),
                ('points', models.PositiveSmallIntegerField()),
                ('goals', models.PositiveSmallIntegerField()),
                ('goals_against', models.PositiveSmallIntegerField()),
                ('goal_difference', models.PositiveSmallIntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballData.Group')),
            ],
        ),
        migrations.CreateModel(
            name='HalfTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals_home_team', models.PositiveSmallIntegerField()),
                ('goals_away_team', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.PositiveIntegerField()),
                ('goals_against', models.PositiveIntegerField()),
                ('wins', models.PositiveIntegerField()),
                ('draws', models.PositiveIntegerField()),
                ('losses', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LeagueTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_caption', models.CharField(max_length=255)),
                ('matchday', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Odds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_win', models.DecimalField(decimal_places=2, max_digits=2)),
                ('draw', models.DecimalField(decimal_places=2, max_digits=2)),
                ('away_win', models.DecimalField(decimal_places=2, max_digits=2)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballData.Fixture')),
            ],
        ),
        migrations.CreateModel(
            name='PenaltyShooutout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals_home_team', models.PositiveSmallIntegerField()),
                ('goals_away_team', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(choices=[(1, 'Keeper'), (2, 'Right-Back'), (4, 'Centre Back'), (3, 'Left-Back'), (6, 'Defensive Midfield'), (8, 'Central Midfield'), (10, 'Attacking Midfield'), (7, 'Right Wing'), (9, 'Centre Forward'), (11, 'Left Wing')], max_length=255)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=255)),
                ('contract_until', models.DateField()),
                ('market_value', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals_home_team', models.PositiveSmallIntegerField()),
                ('goals_away_team', models.PositiveSmallIntegerField()),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballData.Fixture')),
            ],
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('team_name', models.CharField(max_length=255)),
                ('crest_uri', models.URLField(null=True)),
                ('played_games', models.PositiveIntegerField()),
                ('points', models.PositiveIntegerField()),
                ('goals', models.PositiveIntegerField()),
                ('goals_against', models.PositiveIntegerField()),
                ('goal_difference', models.IntegerField()),
                ('wins', models.PositiveIntegerField()),
                ('draws', models.PositiveIntegerField()),
                ('losses', models.PositiveIntegerField()),
                ('league_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballData.LeagueTable')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=255)),
                ('crest_url', models.URLField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='penaltyshooutout',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballData.Result'),
        ),
        migrations.AddField(
            model_name='home',
            name='standing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballData.Standing'),
        ),
        migrations.AddField(
            model_name='halftime',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballData.Result'),
        ),
        migrations.AddField(
            model_name='extratime',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballData.Result'),
        ),
        migrations.AddField(
            model_name='away',
            name='standing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballData.Standing'),
        ),
    ]
