# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-05 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Away',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.IntegerField()),
                ('goals_against', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('draws', models.IntegerField()),
                ('losses', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.IntegerField()),
                ('goals_against', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('draws', models.IntegerField()),
                ('losses', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LeagueTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_caption', models.CharField(max_length=255)),
                ('matchday', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('teamName', models.CharField(max_length=255)),
                ('crestURI', models.URLField()),
                ('played_games', models.IntegerField()),
                ('points', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('goals_against', models.IntegerField()),
                ('goal_difference', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('draws', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('league_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballData.LeagueTable')),
            ],
        ),
        migrations.AddField(
            model_name='home',
            name='standing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballData.Standing'),
        ),
        migrations.AddField(
            model_name='away',
            name='standing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballData.Standing'),
        ),
    ]
