# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awaystanding',
            name='draws',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='awaystanding',
            name='goals',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='awaystanding',
            name='goals_against',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='awaystanding',
            name='losses',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='awaystanding',
            name='wins',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='homestanding',
            name='draws',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='homestanding',
            name='goals',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='homestanding',
            name='goals_against',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='homestanding',
            name='losses',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='homestanding',
            name='wins',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='standing',
            name='draws',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='standing',
            name='goal_difference',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='standing',
            name='goals',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='standing',
            name='goals_against',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='standing',
            name='losses',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='standing',
            name='played_games',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='standing',
            name='points',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='standing',
            name='position',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='standing',
            name='wins',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='matchday',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
