# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_auto_20161223_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuptable',
            options={'get_latest_by': 'matchday'},
        ),
        migrations.AlterModelOptions(
            name='leaguetable',
            options={'get_latest_by': 'matchday'},
        ),
    ]
